[build]
# Use pre-built Docker image from Docker Hub instead of building
dockerImage = "varsharyali336/wtf-is-happening:latest"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
